//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrayDir.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrayDir.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I found a problem with TrayDir!%0D%0DPlease include a description of your problem below.%0DDescription:%0D.
        /// </summary>
        internal static string Email_Body {
            get {
                return ResourceManager.GetString("Email_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrayDir {0}: Bug Report.
        /// </summary>
        internal static string Email_Subject {
            get {
                return ResourceManager.GetString("Email_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrayDir {0}: Bug Report - Unhandled Exception.
        /// </summary>
        internal static string Email_Subject_Unexpected {
            get {
                return ResourceManager.GetString("Email_Subject_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unable to import file..
        /// </summary>
        internal static string Error_ImportFailed {
            get {
                return ResourceManager.GetString("Error_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting.
        ///{0}
        ///{1}.
        /// </summary>
        internal static string ErrorStartingProcess {
            get {
                return ResourceManager.GetString("ErrorStartingProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported to:
        ///{0}.
        /// </summary>
        internal static string ExportedTo {
            get {
                return ResourceManager.GetString("ExportedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string Form_Archive {
            get {
                return ResourceManager.GetString("Form_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Form_Attention {
            get {
                return ResourceManager.GetString("Form_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string Form_Browse {
            get {
                return ResourceManager.GetString("Form_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates on Startup.
        /// </summary>
        internal static string Form_CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("Form_CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Form_Close {
            get {
                return ResourceManager.GetString("Form_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder items as shortcuts.
        /// </summary>
        internal static string Form_CreateFoldersAsShortcuts {
            get {
                return ResourceManager.GetString("Form_CreateFoldersAsShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Form_Delete {
            get {
                return ResourceManager.GetString("Form_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Display Name.
        /// </summary>
        internal static string Form_EditDisplayName {
            get {
                return ResourceManager.GetString("Form_EditDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Ignore RegEx.
        /// </summary>
        internal static string Form_EditIgnoreRegex {
            get {
                return ResourceManager.GetString("Form_EditIgnoreRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Name.
        /// </summary>
        internal static string Form_EditName {
            get {
                return ResourceManager.GetString("Form_EditName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Form_Error {
            get {
                return ResourceManager.GetString("Form_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading icon:
        ///{0}.
        /// </summary>
        internal static string Form_ErrorLoadingIcon {
            get {
                return ResourceManager.GetString("Form_ErrorLoadingIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Form_Exit {
            get {
                return ResourceManager.GetString("Form_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand First Path.
        /// </summary>
        internal static string Form_ExpandFirstPath {
            get {
                return ResourceManager.GetString("Form_ExpandFirstPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Done.
        /// </summary>
        internal static string Form_ExportDone {
            get {
                return ResourceManager.GetString("Form_ExportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide From Tray.
        /// </summary>
        internal static string Form_HideFromTray {
            get {
                return ResourceManager.GetString("Form_HideFromTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide On Minimize.
        /// </summary>
        internal static string Form_HideOnMinimize {
            get {
                return ResourceManager.GetString("Form_HideOnMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Conflict.
        /// </summary>
        internal static string Form_ImportConflict {
            get {
                return ResourceManager.GetString("Form_ImportConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Failed.
        /// </summary>
        internal static string Form_ImportFailed {
            get {
                return ResourceManager.GetString("Form_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Options.
        /// </summary>
        internal static string Form_InstanceOptions {
            get {
                return ResourceManager.GetString("Form_InstanceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Sorting.
        /// </summary>
        internal static string Form_MenuSorting {
            get {
                return ResourceManager.GetString("Form_MenuSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize On Close.
        /// </summary>
        internal static string Form_MinimizeOnClose {
            get {
                return ResourceManager.GetString("Form_MinimizeOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize TrayDir to the System Tray?.
        /// </summary>
        internal static string Form_MinimizeToTray {
            get {
                return ResourceManager.GetString("Form_MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Form_Name {
            get {
                return ResourceManager.GetString("Form_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Instance.
        /// </summary>
        internal static string Form_NewInstance {
            get {
                return ResourceManager.GetString("Form_NewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update Available.
        /// </summary>
        internal static string Form_NewUpdateAvailable {
            get {
                return ResourceManager.GetString("Form_NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of TrayDir is available, do you want to update now?.
        /// </summary>
        internal static string Form_NewUpdateUpdateNow {
            get {
                return ResourceManager.GetString("Form_NewUpdateUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no plugins configured.
        ///Would you like to configure one now?.
        /// </summary>
        internal static string Form_NoPluginsDefined {
            get {
                return ResourceManager.GetString("Form_NoPluginsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration.
        /// </summary>
        internal static string Form_OpenConfiguration {
            get {
                return ResourceManager.GetString("Form_OpenConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to load a configuration from a file? All current data will be lost and TrayDir will restart..
        /// </summary>
        internal static string Form_OpenConfigurationConfirmation {
            get {
                return ResourceManager.GetString("Form_OpenConfigurationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folders in File Explorer When Clicked.
        /// </summary>
        internal static string Form_OpenFoldersInFileExplorerOnClick {
            get {
                return ResourceManager.GetString("Form_OpenFoldersInFileExplorerOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin parameters are invalid.
        ///Verify all required parameters are provided..
        /// </summary>
        internal static string Form_PluginInvalid {
            get {
                return ResourceManager.GetString("Form_PluginInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete &lt;{0}&gt;?.
        /// </summary>
        internal static string Form_PromptDelete {
            get {
                return ResourceManager.GetString("Form_PromptDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Form_Restore {
            get {
                return ResourceManager.GetString("Form_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run As Administrator.
        /// </summary>
        internal static string Form_RunAsAdministrator {
            get {
                return ResourceManager.GetString("Form_RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        internal static string Form_Separator {
            get {
                return ResourceManager.GetString("Form_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show File Extensions.
        /// </summary>
        internal static string Form_ShowFileExtensions {
            get {
                return ResourceManager.GetString("Form_ShowFileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Hidden Files.
        /// </summary>
        internal static string Form_ShowHiddenFiles {
            get {
                return ResourceManager.GetString("Form_ShowHiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Icons In Tray Menu.
        /// </summary>
        internal static string Form_ShowIconsInTrayMenu {
            get {
                return ResourceManager.GetString("Form_ShowIconsInTrayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show TrayMenu on Left Click.
        /// </summary>
        internal static string Form_ShowMenuOnLeftClick {
            get {
                return ResourceManager.GetString("Form_ShowMenuOnLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Minimized.
        /// </summary>
        internal static string Form_StartMinimized {
            get {
                return ResourceManager.GetString("Form_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start With Windows.
        /// </summary>
        internal static string Form_StartWithWindows {
            get {
                return ResourceManager.GetString("Form_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Options.
        /// </summary>
        internal static string Form_TrayOptions {
            get {
                return ResourceManager.GetString("Form_TrayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Folder Menu Icon.
        /// </summary>
        internal static string Form_VirtualFolderMenuIcon {
            get {
                return ResourceManager.GetString("Form_VirtualFolderMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to archive instance:
        ///{0}.
        /// </summary>
        internal static string Instance_Archive {
            get {
                return ResourceManager.GetString("Instance_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete instance:
        ///{0}.
        /// </summary>
        internal static string Instance_Delete {
            get {
                return ResourceManager.GetString("Instance_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Instance.
        /// </summary>
        internal static string Instance_NewInstance {
            get {
                return ResourceManager.GetString("Instance_NewInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restore instance:
        ///{0}.
        /// </summary>
        internal static string Instance_Restore {
            get {
                return ResourceManager.GetString("Instance_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Item_CopyItem {
            get {
                return ResourceManager.GetString("Item_CopyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Item_DeleteItem {
            get {
                return ResourceManager.GetString("Item_DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        internal static string Item_DuplicateItem {
            get {
                return ResourceManager.GetString("Item_DuplicateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand folder in tray menu.
        /// </summary>
        internal static string Item_Expand {
            get {
                return ResourceManager.GetString("Item_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Item_PasteItem {
            get {
                return ResourceManager.GetString("Item_PasteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Item_RenameItem {
            get {
                return ResourceManager.GetString("Item_RenameItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use folder link as shortcut.
        /// </summary>
        internal static string Item_UseAsShortcut {
            get {
                return ResourceManager.GetString("Item_UseAsShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Link to Clipboard.
        /// </summary>
        internal static string MenuItem_CopyLink {
            get {
                return ResourceManager.GetString("MenuItem_CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string MenuItem_Hide {
            get {
                return ResourceManager.GetString("MenuItem_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MenuItem_Open {
            get {
                return ResourceManager.GetString("MenuItem_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location in Command Line.
        /// </summary>
        internal static string MenuItem_OpenCmd {
            get {
                return ResourceManager.GetString("MenuItem_OpenCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location in Command Line (Administrator).
        /// </summary>
        internal static string MenuItem_OpenCmdAdmin {
            get {
                return ResourceManager.GetString("MenuItem_OpenCmdAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Location in File Explorer.
        /// </summary>
        internal static string MenuItem_OpenFileExplorer {
            get {
                return ResourceManager.GetString("MenuItem_OpenFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string MenuItem_Run {
            get {
                return ResourceManager.GetString("MenuItem_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run (Administrator).
        /// </summary>
        internal static string MenuItem_RunAdmin {
            get {
                return ResourceManager.GetString("MenuItem_RunAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all.
        /// </summary>
        internal static string MenuItem_RunAll {
            get {
                return ResourceManager.GetString("MenuItem_RunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string MenuItem_Show {
            get {
                return ResourceManager.GetString("MenuItem_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:.
        /// </summary>
        internal static string Node_Error {
            get {
                return ResourceManager.GetString("Node_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No Name&gt;.
        /// </summary>
        internal static string Node_NoName {
            get {
                return ResourceManager.GetString("Node_NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (No Path Selected).
        /// </summary>
        internal static string Node_NoPathSelected {
            get {
                return ResourceManager.GetString("Node_NoPathSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete plugin:
        ///{0}.
        /// </summary>
        internal static string Plugin_Delete {
            get {
                return ResourceManager.GetString("Plugin_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0}.
        /// </summary>
        internal static string Plugin_ParameterN {
            get {
                return ResourceManager.GetString("Plugin_ParameterN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There exists another plugin with the same name. Would you like to overwrite its configuration?.
        /// </summary>
        internal static string Plugin_SameNameImport {
            get {
                return ResourceManager.GetString("Plugin_SameNameImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete. Plugin currently in use..
        /// </summary>
        internal static string Plugin_UnableToDelete {
            get {
                return ResourceManager.GetString("Plugin_UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another process of TrayDir is already running.
        ///Do you want to start a new one?.
        /// </summary>
        internal static string ProcessRunning {
            get {
                return ResourceManager.GetString("ProcessRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders Bottom.
        /// </summary>
        internal static string Setting_Sorting_FoldersBottom {
            get {
                return ResourceManager.GetString("Setting_Sorting_FoldersBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders Top.
        /// </summary>
        internal static string Setting_Sorting_FoldersTop {
            get {
                return ResourceManager.GetString("Setting_Sorting_FoldersTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string Setting_Sorting_None {
            get {
                return ResourceManager.GetString("Setting_Sorting_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Folder.
        /// </summary>
        internal static string Setting_VFolderColour_Blue {
            get {
                return ResourceManager.GetString("Setting_VFolderColour_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Folder.
        /// </summary>
        internal static string Setting_VFolderColour_Yellow {
            get {
                return ResourceManager.GetString("Setting_VFolderColour_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, TrayDir will check for update on startup.
        /// </summary>
        internal static string Tooltip_CheckForUpdatesOnStartup {
            get {
                return ResourceManager.GetString("Tooltip_CheckForUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder items created will be shortcuts by default.
        /// </summary>
        internal static string Tooltip_CreateFoldersAsShortcuts {
            get {
                return ResourceManager.GetString("Tooltip_CreateFoldersAsShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this instance has a folder as the only item, the
        ///folder&apos;s contents will be used as the main menu structure.
        /// </summary>
        internal static string Tooltip_ExpandFirstPath {
            get {
                return ResourceManager.GetString("Tooltip_ExpandFirstPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide this instance from the sytem tray.
        /// </summary>
        internal static string Tooltip_HideFromTray {
            get {
                return ResourceManager.GetString("Tooltip_HideFromTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, minimizing the window will hide the application.
        /// </summary>
        internal static string Tooltip_HideOnMinimize {
            get {
                return ResourceManager.GetString("Tooltip_HideOnMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new instance.
        /// </summary>
        internal static string Tooltip_InsertInstance {
            get {
                return ResourceManager.GetString("Tooltip_InsertInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path. File or folder not found..
        /// </summary>
        internal static string Tooltip_InvalidPath {
            get {
                return ResourceManager.GetString("Tooltip_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL. Verify it begins with http:// or https:// and contains valid characters.
        /// </summary>
        internal static string Tooltip_InvalidUrl {
            get {
                return ResourceManager.GetString("Tooltip_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set tray menu folder / file sorting.
        /// </summary>
        internal static string Tooltip_MenuSorting {
            get {
                return ResourceManager.GetString("Tooltip_MenuSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, closing the window will not exit the application.
        /// </summary>
        internal static string Tooltip_MinimizeOnClose {
            get {
                return ResourceManager.GetString("Tooltip_MinimizeOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder location in File Explorer when clicking on
        ///them from the System Tray menu.
        /// </summary>
        internal static string Tooltip_OpenFoldersInFileExplorerOnClick {
            get {
                return ResourceManager.GetString("Tooltip_OpenFoldersInFileExplorerOnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always run items from this instance as Administrator.
        /// </summary>
        internal static string Tooltip_RunAsAdministrator {
            get {
                return ResourceManager.GetString("Tooltip_RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show file extensions. E.g. File.txt.
        /// </summary>
        internal static string Tooltip_ShowFileExtensions {
            get {
                return ResourceManager.GetString("Tooltip_ShowFileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, hidden files will be shown inside of folder menu items.
        /// </summary>
        internal static string Tooltip_ShowHiddenFiles {
            get {
                return ResourceManager.GetString("Tooltip_ShowHiddenFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, each menu item will show the icon associated with the file linked.
        /// </summary>
        internal static string Tooltip_ShowIconsInTrayMenu {
            get {
                return ResourceManager.GetString("Tooltip_ShowIconsInTrayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, left clicking on the tray menu item will display the context menu.
        /// </summary>
        internal static string Tooltip_ShowMenuOnLeftClick {
            get {
                return ResourceManager.GetString("Tooltip_ShowMenuOnLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, the application will always start hidden, only visible in system tray.
        /// </summary>
        internal static string Tooltip_StartMinimized {
            get {
                return ResourceManager.GetString("Tooltip_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, the application will start when you log in to your account on Windows.
        /// </summary>
        internal static string Tooltip_StartWithWindows {
            get {
                return ResourceManager.GetString("Tooltip_StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value required.
        /// </summary>
        internal static string Tooltip_ValueRequired {
            get {
                return ResourceManager.GetString("Tooltip_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When virtual folders choose between a yellow folder or blue folder icon.
        /// </summary>
        internal static string Tooltip_VirtualFolderMenuIcon {
            get {
                return ResourceManager.GetString("Tooltip_VirtualFolderMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Virtual Folder and its contents?.
        /// </summary>
        internal static string VirtualFolder_DeleteContents {
            get {
                return ResourceManager.GetString("VirtualFolder_DeleteContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Virtual Folder.
        /// </summary>
        internal static string VirtualFolder_New {
            get {
                return ResourceManager.GetString("VirtualFolder_New", resourceCulture);
            }
        }
    }
}
